[package]
name = "robot"
version = "0.1.0"
authors = ["malique"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gpio-cdev = "0.4.0"
termion = "1.0.0"